ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE kamar DISABLE ROW LEVEL SECURITY;
ALTER TABLE penghuni DISABLE ROW LEVEL SECURITY;
ALTER TABLE pembayaran DISABLE ROW LEVEL SECURITY;
ALTER TABLE perbaikan DISABLE ROW LEVEL SECURITY;
ALTER TABLE booking DISABLE ROW LEVEL SECURITY;
ALTER TABLE pengumuman DISABLE ROW LEVEL SECURITY;
ALTER TABLE pesan DISABLE ROW LEVEL SECURITY;

ALTER TABLE users ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE booking ADD COLUMN IF NOT EXISTS bukti_dp VARCHAR(255);
ALTER TABLE booking ADD COLUMN IF NOT EXISTS batas_waktu TIMESTAMP DEFAULT (CURRENT_TIMESTAMP + INTERVAL '3 days');
ALTER TABLE booking ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
